version: '3.3'

services:
  application:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: careon
    ports:
      - "8090:8090"
    environment:
      SPRING_DATASOURCE_URL: ${DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      GEOCODE_TOKEN: ${GEOCODE_TOKEN}
