spring:
  application:
    name: donation-api
  datasource:
    url: jdbc:postgresql://localhost:5432/donation
    username: postgres
    password: admin
  doc:
    swagger-ui:
      path: /swagger-ui.html
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false


security:
  jwt:
    secret-key: ${JWT_SECRET}
    expiration-time: 3600000
