server:
  port: 8080
#  ssl:
#    key-store: classpath:keystore.p12
#    key-store-password: ${KEY_STORE_PASSWORD}
#    key-store-type: PKCS12
#    key-alias: ${KEY_STORE_ALIAS}

spring:
  application:
    name: donation-api
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  doc:
    swagger-ui:
      path: /swagger-ui.html
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

geolocation:
  api:
    url: https://nominatim.openstreetmap.org
    token: ${GEOCODE_TOKEN}

resilience4j:
  ratelimiter:
    instances:
      nominatimService:
        limitForPeriod: 1
        limitRefreshPeriod: 1s
        timeoutDuration: 500ms

cors:
  allowed-origins: ${FRONT_END_URL}

security:
  jwt:
    secret-key: ${JWT_SECRET}
    expiration-time: 3600000
