name: Deploy com SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Code checkout
        uses: actions/checkout@v2

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Connect to server by SSH
        env:
          SSH_URL: ${{ secrets.SSH_URL }}
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
        run: |
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no "$SSH_USERNAME"@"$SSH_URL" << 'EOF'
            echo "Connected with server!"
            ssh -o StrictHostKeyChecking=no "$SSH_USERNAME"@"$SSH_URL" << 'EOF'
          cd /opt/projects/donation-api
          docker-compose build --no-cache
          if [ $? -eq 0 ]; then
            docker stop donation-api || true
            docker rm donation-api || true
            docker-compose up -d
          else
            echo "Error in the Docker Compose build"
            exit 1
          fi
          EOF
